kafkautils/producer.go
- Add config flags to batch broker calls and increase request timeout periods
- Refactor CommitTransaction() flow to retry timeout errors
=> [EN-1301] [EN-1345] Kafka producer timeout fix for connectors

subscription.go
`subscription` module was always connecting to _Ethereum_ . This will allow to connect to other networks such as _Optimism_
=> Fix subscription network

connector.go, kafkautils/producer.go
- Remove manual timeout for `AbortTransaction()`
- Implement delivery report channel
- Reduce commit interval
=> Refactor Kafka tx timeout

connector.go, examples/compound/compound.go, examples/compound/local.yaml, examples/ethereum/ethereum.go, kafkautils/topic.go
Turn off protoregistry in dev mode and update kafka usage
=> [EN-1323] Turn off protoregistry in dev mode

subscription.go
This will force periodical garbage collection so as not to run out of memory in a busy connector.
=> [EN-1435] [EN-1437] Force periodical garbage collection

subscription.go
Reverts nakji-network/connector#36
The issue persists. This fix didn't work.
=> Revert "[EN-1435] [EN-1437] Force periodical garbage collection"

chain/ethereum.go, chain/ethereum_test.go, connector.go, kafkautils/mocks/mock_producer.go, kafkautils/producer.go, subscription.go, subscription_test.go
Refactors Connector lib to improve backfill
=> [EN-1480] Refactor Connector lib backfill

protoregistry/client.go
* fix docker container permission issue
=> [COR-126] Get rid of nfs server 

connector.go, connector_test.go, subscription.go, subscription_test.go
- Remove `MsgType` field from `Connector`
- Rename `Unsubscribe` with `Close` in Subscription
=> Remove msg type

chain/ethereum.go, connector.go, subscription/subscription.go, subscription/subscription_test.go
- Refactor backfill to handle rate limit error (BSC / BNB Chain)
- Refactor subscription to handle closed channel errors
=> Refactor subscription and backfill

connector.go, kafkautils/consumer.go, kafkautils/producer.go
=> [COR-107] Nakji core indexer latency

connector.go
COR-106
Add timeout so tracing does not cause connectors to hang
=> [COR-106] Add otel collector timeout

chain/ethereum/subscription.go
- Add func TransactionByHash
- Add func TransactionSender
- Fix error logs
=> [INT-406] Update ethereum Subscription

chain/ethereum/ethereum.go
- Add func BackfillFrom
- Add field *ethclient.Client to ethereum.Connector
=> Update ethereum Connector

.github/workflows/go.yml, protoregistry/client.go, protoregistry/client_test.go, protoregistry/payload.go, protoregistry/prtest/prtest.proto.desc
1. Add support for importing `.proto` from separate modules
2. Get descriptor info from the `.pb.go`
3. Don't need to generate `.desc` files anymore
=> [COR-198] Add support for import proto from separate modules

connector.go, kafkautils/message.go
- Create batching routine for kafka transactions
- Remove unused `topicStr` property
=> [INT-385] Create batch produce routine

chain/ethereum/ethereum.go
- Add retry mechanism for func HistoricalEvents
=> Add retry mechanism for func HistoricalEvents

chain/ethereum/ethereum.go, chain/ethereum/subscription.go, kafkautils/producer.go
- Remove unnecessary error logs
=> [COR-211] Remove unnecessary error logs

kafkautils/kafkautils_test.go, kafkautils/stream.go, kafkautils/stream_test.go, kafkautils/topic_test.go, kafkautils/topictyperegistry.go, kafkautils/topictyperegistry_test.go
@cnkarz go tests in kafkautils package were never run because you didn't write the TestMain properly.
You need to add this line at the end of TestMain function: `os.Exit(m.Run())`
After I've fixed TestMain function, go tests in kafkautils package failed. Can you fix them by adding new commit to this PR?
=> Fix go test never fails

chain/ethereum/ethereum.go, chain/ethereum/subscription.go
Refactor backfill to have a simple retry mechanism with exponential backoff.
=> Refactor backfill with retry

connector.go, protoregistry/client.go
=> [COR-268] Fix minor issues
