nakji-network/connector

kafkautils/consumer.go, kafkautils/producer.go
`string` was replaced with `Topic` but the interface was forgotten. So several connectors implementing this interface don't compile.
also `transactionsInitialized` was not used.
=> [EN-1104] Change kafkautils WriteAndCommit param

connector.go, kafkautils/consumer.go, kafkautils/mocks/mock_producer.go, kafkautils/producer.go
Existing mock is for the previous version. It breaks connector tests. This PR replaces it with the latest interface.
=> [EN-1104] Update kafka producer mock

connector.go, kafkautils/mocks/mock_producer.go, kafkautils/producer.go
refs: https://blep.atlassian.net/browse/EN-1236?atlOrigin=eyJpIjoiN2RiNDVhYWNmODdhNDFlZmJiZjdjMjAyYmZiZWMwYTYiLCJwIjoiaiJ9
Changes:
- removes MakeQueueTransactionSink
- replaces connector.Producer field with ProducerInterface so we can mock it out in our tests in blep.ai
=> [EN-1236] Use ProducerInterface instead of Producer

kafkautils/producer.go
Several connectors failing with "queue buffer overflow" errors and "transaction
timeout errors".
This change in config will hopefully fix this.
=> Tweak producer configs to try and fix restart issues in connectors.

kafkautils/producer.go
I misread the last time. I thought default for transaction timeout was 1sec. Turns out it was 1min. Trying out again with 10mins.
We should change this in the future so that configuration changes can be done without making changes to the code.
=> Change transaction timeout to 10mins

connector.go, go.mod, go.sum, kafkautils/producer.go
Currently, a transaction lifecycle for a Kafka producer is ordered in a way that a message write ends with `BeginTransaction()`. This will keep the producer waiting for a produce and commit calls for too long. This might have unintended consequences and maybe hard to debug.
This PR puts the steps in an order.
=> Reorder Producer transaction actions

gocryptotrader/go.mod
Latest version of the lib breaks our forked lib. This will short-circuit dependency import and point to our internal lib.
=> Replace dependency

connector.go, kafkautils/key.go, kafkautils/producer.go
- Update kafka lib to accept messages without key.
- Including a delivery channel bypasses global event processing. This PR removes that channel.
=> Disable Kafka msg delivery chan

connector.go, examples/compound/cmd/compound/main.go, examples/ethereum/cmd/ethereum/main.go, examples/go.mod
Remove `NewProducerConnector()` and `NewConsumerConnector()` and point to `NewConnector()` factory method
=> Revert to single NewConnector method

subscription.go
Sometimes websocket connection closes with `unexpected EOF` error. This PR allow reconnection on such occasions.
=> [EN-1411] Handle EOF error on websocket conn

kafkautils/producer.go
This is for applying the batched transactions fix on older connectors that are not yet fully using the connector library. That way, we can apply the producer tx timeout fixes with little or no refactoring.
=> Batched messages

connector.go, subscription.go
This PR will create a kafka Produce channel in its constructor automatically.
There are also minor changes as:
- Add error log to RPC subscription fatal errors
- Handle RPC go away error
=> [EN-1471] Automate event produce channel

chain/solana.go, go.mod, go.sum
Temporarily refactor it to use `connector` lib and disable the backfill feature, because it is not using ws client somehow. Currently it's using http polling to get the block data, we need to do more refactoring work on it in the future.
=> [EN-1503] Refactor solana client

subscription.go
This will allow users to have a handle to the ETH client and call the network manually when needed.
=> Export ETH client

connector.go, kafkautils/mocks/mock_producer.go, kafkautils/producer.go
Removes `WriteKafkaMessages()` and points callers to `ProduceMsg()` function. They are basically doing the same thing.
=> Remove duplicate kafka produce msg functions

connector.go, go.mod, go.sum, manifest.go
It's hard to migrate some legacy connectors to the new repo, so we need a way to create manifest manually.
=> [EN-1502] Refactor manifest creation for legacy connectors

protoregistry/client.go, protoregistry/client_test.go, protoregistry/prtest/prtest.proto.desc
COR-126 (issue)
1. Stop connectors from using nfs server, migrate all proto descriptor files from nfs server to the database
2. Producer connectors must generate descriptor file now (instead of sink connectors) when registering proto.
=> [COR-126] Get rid of nfs server

monitor/otel.go
Set global meter provider in `InitMeterProvider` in monitor package. This is to fix a bug in streamserver
=> [COR-178] Fix MeterProvider bug

chain/ethereum/go.mod, chain/ethereum/go.sum, chain/ethereum/subscription.go, chain/ethereum/subscription_test.go, connector.go, kafkautils/consumer.go, kafkautils/message.go, kafkautils/producer.go, monitor/baggage.go
Fixes unresolved issues from adding tracing for `0.2.0` release including:
* Removes context from `Log` in Ethereum subscription and `kafkautils.Message` and uses baggage and span instead
* Return baggage in `monitor.NewLatencyBaggage` for cases where baggage is not passed using context.
* Update usage of `Log` and `kafkautils.Message` to reflect these changes
* Move `ctx` to first parameter  in several functions in `producer.go` to match [convention](https://github.com/golang/go/wiki/CodeReviewComments#contexts). Passing context between functions is retained rather than passing `nil` for empty span or baggage because it's cleaner and functions that extract baggage or spans from context automatically handle the case where there is no span or baggage. No need to check for `nil` values.
* …
=> [COR-177] Fix unresolved latency and metrics issues

monitor/metric.go, monitor/metric_test.go
Fixes a couple of issues from initial latency PR. 
Latencies were exported in microseconds, so the values fell outside of all buckets for histogram. Latencies are still recorded in microseconds, but exported in float64 milliseconds. 
Example of current data from prod:
```
latency_connector_histogram_bucket{Connector="sushiswap",Env="prod",job="streamserver",le="0"} 0
latency_connector_histogram_bucket{Connector="sushiswap",Env="prod",job="streamserver",le="5"} 0
latency_connector_histogram_bucket{Connector="sushiswap",Env="prod",job="streamserver",le="10"} 0
latency_connector_histogram_bucket{Connector="sushiswap",Env="prod",job="streamserver",le="25"} 0
latency_connector_histogram_bucket{Connector="sushiswap",Env="prod",job="streamserver",le="50"} 0 …
```
=> [COR-177] Latency Fixes

connector.go, kafkautils/producer.go
Deprecate older message producing functions in `connector` and `kafkautils.producer`.
=> [INT-385] Deprecate old connector functions

chain/ethereum/ethereum.go, chain/ethereum/subscription.go
Removes channel closing by sender to allow multithreading
=> Refactor Backfill

monitor/otel.go
- Discard all otel logs because they dont use our standard format so that google cloud thinks they are error logs making it difficult to debug.
- This is a quick fix. In the future, we may want to implement an adaptor to make otel log compatible with zero log.
=> Discard otel logs

connector.go
Randomize Kafka producer ID for backfill jobs. This way we will be able to run multiple jobs at once and they will be able to push to same topic without being fenced.
=> [INT-431] Enable randomized producer id

chain/ethereum/ethereum.go
This PR reduces block chunk size from 3000 to 1000 to avoid RPC call failures for either too large block intervals or too many events.
=> Reduce block chunk size

chain/ethereum/ethereum.go
Failed backfill intervals are split into two to process in two steps. However, this division can go all the way down to 1 block. 
In that case, the routine will just loop. This PR fixes that.
=> Increment interval start

connector.go
As per discussion here: https://blep.atlassian.net/browse/COR-268, we don't want connectors to crash
=> [COR-268] Do not let source connectors crash

chain/ethereum/ethereum.go, chain/ethereum/subscription.go
Some backfills include filtering by event `Topic`. Previously, we only filtered by `Address` and/or block height. 
This PR adds the functionality to filter by topic.
=> [INT-374][INT-440] Add Filter Query to Backfill
